const cardsBandas = [
    { id: "andres",          image: '/images/andresCalamaro.png'          },
    { id: "arbol",           image: '/images/arbol.png'                   },
    { id: "attaque77",       image: '/images/attaque77.png'               },
    { id: "babasonicos",     image: '/images/babasonicos.png'             },
    { id: "babasonicos2",    image: '/images/babasonicos2.png'            },
    { id: "babasonicos3",    image: '/images/babasonicos3.png'            },
    { id: "babasonicos4",    image: '/images/babasonicos4.png'            },
    { id: "callejeros",      image: '/images/callejeros.png'              },
    { id: "cuartetoDeNos",   image: '/images/cuartetoDeNos.png'           },
    { id: "cuartetoDeNos2",  image: '/images/cuartetoDeNos2.png'          },
    { id: "cuartetoDeNos3",  image: '/images/cuartetoDeNos3.png'          },
    { id: "cuartetoDeNos4",  image: '/images/cuartetoDeNos4.png'          },
    { id: "divididos",       image: '/images/divididos.png'               },
    { id: "estelares",       image: '/images/estelares.png'               },
    { id: "estelares2",      image: '/images/estelares2.png'              },
    { id: "intoxicados",     image: '/images/intoxicados.png'             },
    { id: "intoxicados2",    image: '/images/intoxicados2.png'            },
    { id: "laBeriso",        image: '/images/laBeriso.png'                }, 
    { id: "laBeriso2",       image: '/images/laBeriso2.png'               }, 
    { id: "laVelaPuerca",    image: '/images/laVelaPuerca.png'            }, 
    { id: "lasPastillas",    image: '/images/lasPastillasDelAbuelo.png'   },
    { id: "lasPastillas2",   image: '/images/lasPastillasDelAbuelo2.png'  },
    { id: "lasPastillas3",   image: '/images/lasPastillasDelAbuelo3.png'  },
    { id: "lasPastillas4",   image: '/images/lasPastillasDelAbuelo4.png'  },
    { id: "losAutenticos",   image: '/images/losAutenticosDecadentes.png' },
    { id: "losPiojos",       image: '/images/losPiojos.png'               },
    { id: "losTipitos",      image: '/images/losTipitos.png'              },
    { id: "noTeVaAGustar",   image: '/images/noTeVaAGustar.png'           },
    { id: "noTeVaAGustar2",  image: '/images/noTeVaAGustar2.png'          },
    { id: "manchaDeRolando", image: '/images/manchaDeRolando.png'         },
    { id: "patricioRey",     image: '/images/patricioRey.png'             },
    { id: "turf",            image: '/images/turf.png'                    },
    { id: "fondo",           image: '/images/fondoDeCartas.png'           },
  ];
  
export default cardsBandas;  